# Generated by Django 3.1.2 on 2020-12-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='intructor',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='assignments',
            field=models.ManyToManyField(null=True, to='main.Assignment'),
        ),
        migrations.AddField(
            model_name='student',
            name='assignments',
            field=models.ManyToManyField(null=True, to='main.Assignment'),
        ),
    ]
