# Generated by Django 3.1.2 on 2021-03-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='assignments',
            field=models.ManyToManyField(null=True, related_name='asisgnments', to='main.Assignment'),
        ),
    ]
