# Generated by Django 3.1.2 on 2021-03-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210331_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='assignments',
            field=models.ManyToManyField(related_name='assignments', to='main.Assignment'),
        ),
    ]
