# Generated by Django 3.1.2 on 2020-12-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201222_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='assignments',
            field=models.ManyToManyField(to='main.Assignment'),
        ),
        migrations.AlterField(
            model_name='student',
            name='assignments',
            field=models.ManyToManyField(to='main.Assignment'),
        ),
    ]
