# Generated by Django 3.1.2 on 2020-12-02 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201202_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
