# Generated by Django 3.1.2 on 2021-04-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210331_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='describtion',
        ),
        migrations.AddField(
            model_name='assignment',
            name='Ess',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='pOvershoot',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='riseTime',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='setTime',
            field=models.FloatField(null=True),
        ),
    ]
