# Generated by Django 3.1.2 on 2020-12-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='major',
            field=models.CharField(default='Not mentioned', max_length=64),
        ),
    ]
