# Generated by Django 3.1.2 on 2021-01-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210124_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='name',
            new_name='subject',
        ),
    ]
