# Generated by Django 3.1.2 on 2021-04-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_assignment_describtion'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='controller',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
