# Generated by Django 3.1.2 on 2021-01-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210124_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='intructor',
            new_name='instructor',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='assignments',
            field=models.ManyToManyField(related_name='asisgnments', to='main.Assignment'),
        ),
    ]
