# Generated by Django 3.1.2 on 2021-05-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_assignment_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='simulator',
            field=models.CharField(choices=[('Cruise Control', 'Cruise Control'), ('Water', 'Water'), ('Servo Motor', 'Servo Motor')], max_length=64, null=True),
        ),
    ]
