# Generated by Django 3.1.2 on 2021-05-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210501_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='Pass',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
