# Generated by Django 3.1.2 on 2021-01-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210124_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='describtion',
            field=models.TextField(null=True),
        ),
    ]
