# Generated by Django 3.1.2 on 2021-05-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_submission_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='parameters',
            field=models.TextField(null=True),
        ),
    ]
