# Generated by Django 3.1.2 on 2021-01-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210126_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='simulator',
            field=models.CharField(choices=[('Cruise Control', 'Cruise Control'), ('Adaptive Cruise control', 'Adaptive Cruise control'), ('Servo Motor', 'Servo Motor')], max_length=64, null=True),
        ),
    ]
