# Generated by Django 3.1.2 on 2021-03-26 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210126_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.assignment'),
        ),
    ]
