# Generated by Django 3.1.2 on 2021-06-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210514_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='describtion',
            new_name='description',
        ),
    ]
