# Generated by Django 3.1.2 on 2021-03-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_course_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assignments',
        ),
        migrations.AddField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(to='main.Assignment'),
        ),
    ]
