# Generated by Django 3.1.2 on 2021-07-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210705_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='setPoint',
            field=models.FloatField(null=True),
        ),
    ]
